// Optional native Postgres runner when Docker is unavailable.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync, unlinkSync } from "node:fs";
import { resolve, join } from "node:path";

const url = new URL(process.env.DATABASE_URL ?? "");
if (
	url.hostname !== "127.0.0.1" ||
	url.pathname !== "/agentic_inbox_prototype" ||
	url.username !== "inbox"
) {
	throw new Error(
		"Native runner only supports the isolated local prototype database generated by pnpm setup:local.",
	);
}
const bin =
	process.env.PG_BIN ??
	execFileSync("pg_config", ["--bindir"], { encoding: "utf8" }).trim();
const data = resolve(".local/postgres");
const run = (name, args, extra = {}) =>
	execFileSync(join(bin, name), args, { stdio: "inherit", ...extra });
if (process.argv[2] === "stop") {
	run("pg_ctl", ["-D", data, "-m", "fast", "-w", "stop"]);
	process.exit(0);
}
mkdirSync(resolve(".local"), { recursive: true });
if (!existsSync(join(data, "PG_VERSION"))) {
	const passwordFile = resolve(".local/init-password");
	writeFileSync(passwordFile, decodeURIComponent(url.password), {
		mode: 0o600,
	});
	try {
		run("initdb", [
			"-D",
			data,
			"-U",
			"inbox",
			"--auth=scram-sha-256",
			"--pwfile",
			passwordFile,
			"--encoding=UTF8",
			"--locale=C",
		]);
	} finally {
		unlinkSync(passwordFile);
	}
}
if (!existsSync(join(data, "postmaster.pid"))) {
	run("pg_ctl", [
		"-D",
		data,
		"-l",
		resolve(".local/postgres.log"),
		"-o",
		`-h 127.0.0.1 -p ${Number(url.port)} -k ${resolve(".local")}`,
		"-w",
		"start",
	]);
}
const args = ["-h", "127.0.0.1", "-p", url.port, "-U", "inbox"];
const env = { ...process.env, PGPASSWORD: decodeURIComponent(url.password) };
const exists = execFileSync(
	join(bin, "psql"),
	[
		...args,
		"-d",
		"postgres",
		"-tAc",
		"SELECT 1 FROM pg_database WHERE datname = 'agentic_inbox_prototype'",
	],
	{ env, encoding: "utf8" },
).trim();
if (!exists) run("createdb", [...args, "agentic_inbox_prototype"], { env });
console.log(
	`Local Postgres ready on 127.0.0.1:${url.port}. Credentials are in .env.`,
);
